### ISSUE TITLE
UserAgent: truncated (chunked) response when fetching from html5.validator.nu

### ISSUE THREAD

**Issue by JonnyJD** [libwww-perl/libwww-perl#36] opened 2013-03-21 01:31 UTC
I was getting weird errors (about invalid json) when posting html files to html5.validator.nu (using LWP::UserAgent) and getting json files as reponse.
I tracked it down to the server sending chunks and LWP only receiving the first chunk.
However, there must be something wrong in bigger detail, since other servers sending chunks work just fine.
LWP also takes a long time (which is partly fixed using Net::HTTP 6.06.
The problem might be in a dependency of LWP (Net::HTTP?), but I don't have enough knowledge to track it further down and LWP is what I am actually using.

This can be reproduced with

```
./chunked.pl < error115.html
```

With (chunked.pl)[http://tickets.musicbrainz.org/secure/attachment/10639/chunked.pl] and (as an example) (error115.html)[http://tickets.musicbrainz.org/secure/attachment/10636/error115.html].
The html file is not special, I get truncation with many other files (with invalid html5) too, sometimes with chunks as small as 2.6 kb. The server (http://html5.validator.nu/?out=json) is special. I couldn't find other servers where this occurs, even validator.nu (when online) and validator.w3.org/nu work fine. 
The server runs Jetty 6.1.26, which in itself is no problem (validator.w3.org is also a jetty server).

So yes, there is something "interesting" going on on the server, but other clients (tested my browser and curl) don't have problems with the server.
I tested from my machine, a VM (on my machine) and on a server in a different country.
Upgraded LWP, Net::HTTP and IO::Socket, which didn't help (only failing a bit faster).
I tried downgrading every version down to Net::HTTP 6.00, but that didn't help.

The test script also tests with WWW::Curl::Simple for a comparision. You can disable that part if you don't have the module at hand.
Important is that error115.html gives > 31000 bytes as response, and the response should be valid json (the script shows the last 68 characters and should end with "]}".

This problem is also tracked ("downstream") as:
http://tickets.musicbrainz.org/browse/MBS-6041

**Comment by gpoul** [comment] 2015-10-02 17:41
I tested this on Fedora Beta 23 with Perl 5.22.0 and perl-libwww-perl-6.13-3.fc23.noarch and it looks fine:

$ ./chunked.pl <error115.html 
trying LWP:
	POST with length 32348 to http://html5.validator.nu/?out=json
	length of response: 35518
	...ract":" Artist)\"><bdi>Test A","hiliteStart":10,"hiliteLength":5}]}

Not sure whether this was fixed in libwww-perl or whether the behavior of the test server changed.

**Comment by genio** [comment] 2019-05-13 13:05
Since this can't really be reproduced right now, I'm going to close this out for the time being. If you can come up with a good example case for the current releases, please let us know.

**Closed by genio** 2019-05-13 13:05 UTC
