### ISSUE TITLE
Final MIME delimiter requires following linefeed [rt.cpan.org #65710]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#223] opened 2017-03-31 19:02 UTC
Migrated from [rt.cpan.org#65710](https://rt.cpan.org/Ticket/Display.html?id=65710) (status was 'open')

Requestors:
* richard.barnes@msci.com

From richard.barnes@msci.com on 2011-02-14 11:59:23:
```
HTTP::Message parses MIME messages.  As part of the parsing process, the
subroutine _parts strips of the final delimiter and any following text
using the line:

	    $str =~ s/\r?\n--\Q$b\E--\r?\n.*//s;

where $str holds the message and $b the boundary.

This pattern requires at least a \n after the boundary in order to match.

I am trying to interact with a web service, using the XML::Compile::SOAP
modules, which use HTTP::Message, where the MIME response ends
immediately after the final --boundary-- delimiter without any further
line-ending.

According to rfc2045 (and following), no characters following the final
delimiter are necessary and the linefeed is not part of the delimiter:

     multipart-body := [preamble CRLF]
                       dash-boundary transport-padding CRLF
                       body-part *encapsulation
                       close-delimiter transport-padding
                       [CRLF epilogue]

     transport-padding := *LWSP-char
                          ; Composers MUST NOT generate
                          ; non-zero length transport
                          ; padding, but receivers MUST
                          ; be able to handle padding
                          ; added by message transports.

     close-delimiter := delimiter "--"

I'm using HTTP::Message 5.835, perl 5.10.1, Cygwin_NT-6.1

Thanks,
Richard
```

From tom@eborcom.com on 2014-09-20 13:23:32:
```
Thank you for reporting this bug.  It duplicates https://rt.cpan.org/Ticket/Display.html?id=79239 which has since been fixed.
```

**Comment by colinnewell** [comment] 2017-04-12 18:04
This appears to be a dead issue.

**Comment by genio** [comment] 2017-04-12 23:41
This issue is a duplicate of https://github.com/libwww-perl/HTTP-Message/issues/71 which we think is fixed.

**Closed by genio** 2017-04-12 23:41 UTC
Labels: Duplicate
