### ISSUE TITLE
NTLM Proxy Authentication

### ISSUE THREAD

**Issue by thoke** [libwww-perl/libwww-perl#59] opened 2014-07-24 16:21 UTC
I'm working with a Microsoft Forefront Threat Management Gateway web proxy and I'm not able to get NTLM authentication (required at the proxy) working.

Here's my example script:

``` perl
use strict;
use warnings;

use LWP::UserAgent;

my $url = 'https://webserver.example.com/test.txt';

# MS TMG
my $proxy_server = 'http://mstmgproxy.example.com';
my $proxy_port = 8080;

# Proxy credentials
my $proxy_username = 'username';
my $proxy_password = 'password';

my $p_str = $proxy_server . ":" . $proxy_port;
if ( $p_str =~ m{(.*)//(.*)} ) {
    $p_str = "$1//$proxy_username:$proxy_password\@$2";
}
else {
    $p_str = "$proxy_username:$proxy_password\@$p_str";
}

my $ua  = LWP::UserAgent->new;
$ua->proxy( ['http', 'https'] => $p_str );

my $response = $ua->get($url);

if ( $response->is_success ) {
    print $response->decoded_content;
}
else {
    die $response->status_line;
}
```

The result is is the following output:

```
500 establishing SSL tunnel failed: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ) at ./example.pl line 34.
```

One issue (the "500 establishing SSL tunnel failed" message) is taken care of in pull request #56. However, that still doesn't resolve the issue.

I never actually see LWP::Authen::Ntlm get dispatched to even attempt to fulfill the authentication.

The above script works with anonymous  or basic auth proxies, but not NTLM.

**Comment by genio** [comment] 2019-05-13 13:13
It looks like you're relying on the fall-through to basic auth. You need to set the credentials() as seen in https://metacpan.org/pod/LWP::Authen::Ntlm#SYNOPSIS

I'm going to close this out for now since I cannot reproduce your error. Please don't hesitate to reopen if I'm missing something.

**Closed by genio** 2019-05-13 13:13 UTC
