### ISSUE TITLE
XML unparsable due to unwarranted decoding [rt.cpan.org #52572]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#215] opened 2017-03-31 19:00 UTC
Migrated from [rt.cpan.org#52572](https://rt.cpan.org/Ticket/Display.html?id=52572) (status was 'open')

Requestors:
* IKEGAMI@cpan.org

From ikegami@cpan.org on 2009-12-08 21:05:30:
```
Hello,

HTTP::Message's decoded_content properly removes the content encoding
from XML responses but it now removes the character encoding too. That's
making XML downloads unparseable.

In order to parse an XML document returned by decoded_content, one must
first A) loosely parse the XML to extract the encoding from the <?xml?>
tag, and B) re-encode the XML according to that type.

There's a reason the base type for the XML MIME type is "application",
but HTTP::Message violates it.

    $ perl -e'
        use strict;
        use warnings;

        use Test::More tests => 4;

        use Encode           qw( encode );
        use LWP              qw( );
        use XML::LibXML      qw( );
        use PerlIO::encoding qw( );

        sub check {
            my ($file, $test) = @_;
            if (!eval {
                my $name =
                    XML::LibXML->new()
                    ->parse_string($file)
                    ->documentElement()
                    ->textContent();
                is($name, "\x{C9}ric", $test);
                1;
            }) {
                fail($test)
                    or diag("died with $@");
            }
        }

        {
            my $builder = Test::More->builder;
            local $PerlIO::encoding::fallback = Encode::PERLQQ();
            binmode $builder->output,         ":encoding(US-ASCII)";
            binmode $builder->failure_output, ":encoding(US-ASCII)";
            binmode $builder->todo_output,    ":encoding(US-ASCII)";
        }

        for my $enc (qw( cp850 UTF-16le )) {
            my $file = encode($enc,
                ($enc =~ /^UTF-/ ? "\x{FEFF}" : "") .
                qq{<?xml version="1.0" encoding="$enc"?>\n} .
                qq{<root>\x{C9}ric</root>\n}
            );

            check($file, "$enc direct");

            my $headers = HTTP::Headers->new(Content_Type =>
"application/xml");
            my $response = HTTP::Response->new(200, "OK", $headers, $file);

            check($response->decoded_content(), "$enc from response");
        }
    '
    1..4
    ok 1 - cp850 direct
    not ok 2 - cp850 from response
    #   Failed test 'cp850 from response'
    #   at -e line 20.
    #          got: '\x{251c}\x{00eb}ric'
    #     expected: '\x{00c9}ric'
    ok 3 - UTF-16le direct
    not ok 4 - UTF-16le from response
    #   Failed test 'UTF-16le from response'
    #   at -e line 14.
    # died with :1: parser error : Blank needed here
    #
\x{3e3f}\x{3c0a}\x{6f72}\x{746f}\x{c33e}\x{7289}\x{6369}\x{2f3c}\x{6f72}\x{746f}\x{0a3e}
    # ^
    # :1: parser error : parsing XML declaration: '?>' expected
    #
\x{3e3f}\x{3c0a}\x{6f72}\x{746f}\x{c33e}\x{7289}\x{6369}\x{2f3c}\x{6f72}\x{746f}\x{0a3e}
    # ^
    # :1: parser error : Start tag expected, '<' not found
    #
\x{3e3f}\x{3c0a}\x{6f72}\x{746f}\x{c33e}\x{7289}\x{6369}\x{2f3c}\x{6f72}\x{746f}\x{0a3e}
    #            ^
    # Looks like you failed 2 tests of 4.

The bug was introduced some version after 5.814 but before 5.828.
Probably 5.827 according to CHANGES.

Workaround if you're specifically expecting XML:

    my $xml = $reponse->decoded_content($response, charset => 'none');

Generic workaround:

    sub _decoded_content {
        my ($mess, %opts) = @_;

        if (!$opts{charset} || $opts{charset} ne 'none') {
            if ($HTTP::Message::VERSION >= 5.527) {
                $opts{charset} = 'none' if $mess->content_is_xml();
                return $mess->decoded_content(%opts);
            }
        }

        return $mess->decoded_content(%opts);
    }


    #$response->decoded_content(...);  # Buggy
    my $file = _decoded_content($response, ...);

Eric "ikegami" Brine
```

From srezic@cpan.org on 2009-12-18 17:32:22:
```
On Tue Dec 08 16:05:30 2009, ikegami wrote:
> Hello,
> 
> HTTP::Message's decoded_content properly removes the content encoding
> from XML responses but it now removes the character encoding too.
> That's
> making XML downloads unparseable.
[...]

Ah, I stumbled over this problem, too. Vote++

Regards,
    Slaven
```

From gaas@cpan.org on 2009-12-18 19:51:45:
```
I would like for $mess->decoded_content to continue to decode the charset.  There are many 
applications where you want to treat XML as text.  This is also needed when feeding XML to 
HTML::Parser which LWP does.

I propose that the default behaviour should be to decode the text and then to remote the 
encoding declaration if present.  The following patch does that: <http://github.com/gisle/libwww-
perl/commit/20d9c7d097972f575c9c77cc408cc066556a00c5>

I'm thinking about adding some option to decoded_content to get the behaviour you actually 
asked for; basically "charset => 'none_for_xml'".  I don't actaully want to call it that.
```

From ikegami@adaelis.com on 2009-12-18 21:16:41:
```
On Fri, Dec 18, 2009 at 2:51 PM, Gisle_Aas via RT <
bug-libwww-perl@rt.cpan.org> wrote:

> <URL: https://rt.cpan.org/Ticket/Display.html?id=52572 >
>
>  I'm thinking about adding some option to decoded_content to get the
> behaviour you actually
> asked for; basically "charset => 'none_for_xml'".  I don't actaully want to
> call it that.
>

Just an idea, but how about new attribute xml_as_text => 0/1 or xml_as_bin
=> 0/1?

text=F/bin=T treats xml as application/ and keeps the char encoding
text=T/bin=F treats xml as text/ and removes the char encoding

A default of text=T/bin=F would allow people to pretend XML is HTML.
(Compatible with >=5.827)
A default of text=F/bin=T would allow people to treat XML as XML (Compatible
with <5.827)

By creating a new attribute, you create the perfect place to document the
exceptional behaviour.

- ELB
```

**Comment by toreanderson** [comment] 2017-04-16 09:29
I've come across the same issue. It appears `LWP::Simple` (from libwww-perl version 6.15 on Fedora 25) is recoding the UTF-8 web server response to Latin-1, even though there is nothing nowhere that even hints at this data being in any other character set than UTF-8.

The URL in question is http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002 .

The system locale is also set to UTF-8, and both Wget and Curl gets it right, as shown below:

```
$ locale
LANG=nn_NO.utf8
LC_CTYPE="nn_NO.utf8"
LC_NUMERIC="nn_NO.utf8"
LC_TIME="nn_NO.utf8"
LC_COLLATE="nn_NO.utf8"
LC_MONETARY="nn_NO.utf8"
LC_MESSAGES="nn_NO.utf8"
LC_PAPER="nn_NO.utf8"
LC_NAME="nn_NO.utf8"
LC_ADDRESS="nn_NO.utf8"
LC_TELEPHONE="nn_NO.utf8"
LC_MEASUREMENT="nn_NO.utf8"
LC_IDENTIFICATION="nn_NO.utf8"
LC_ALL=
$ wget -qO- 'http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002' | grep '<farge>' | hexdump -C
00000000  20 20 20 3c 66 61 72 67  65 3e 47 72 c3 b8 6e 6e  |   <farge>Gr..nn|
00000010  3c 2f 66 61 72 67 65 3e  0a                       |</farge>.|
00000019
$ curl -s 'http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002' | grep '<farge>' | hexdump -C
00000000  20 20 20 3c 66 61 72 67  65 3e 47 72 c3 b8 6e 6e  |   <farge>Gr..nn|
00000010  3c 2f 66 61 72 67 65 3e  0a                       |</farge>.|
```

So here the byte sequence `c3 b8` is used to represent the Norwegian character `ø`. That's correct UTF-8.

However, `LWP::Simple` gets it wrong:

```
$ perl -MLWP::Simple -e "print get('http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002')" | grep -a '<farge>' | hexdump -C
00000000  20 20 20 3c 66 61 72 67  65 3e 47 72 f8 6e 6e 3c  |   <farge>Gr.nn<|
00000010  2f 66 61 72 67 65 3e 0a                           |/farge>.|
00000018
```

So here `ø` character is instead represented with the byte `f8`. That would be correct for data in Latin-1.

I also inspected the data being sent on the wire with Wireshark to see if it possible that the server is at fault by giving an incorrect character set, but it does not appear like that is the case. The request is as follows:

```
GET /system/mobilapi?registreringsnummer=EL10002 HTTP/1.1
TE: deflate,gzip;q=0.3
Connection: TE, close
Host: www.vegvesen.no
User-Agent: LWP::Simple/6.15 libwww-perl/6.15
```

Resulting in the following response from the server:

```
HTTP/1.1 200 OK
Date: Sun, 16 Apr 2017 09:16:00 GMT
Server: Apache-Coyote/1.1
Expires: Sun, 16 Apr 2017 09:16:00 GMT
Cache-Control: private, max-age=0
ETag: content_B151594F9BF3D3BA4DA286F965D5470D8718DB5B
Content-Type: text/xml;charset=utf-8
Content-Length: 7791
Set-Cookie: JSESSIONID=F8E5DCEE746921996E862D0D51754F1C; Path=/; HttpOnly
Connection: close
Vary: Accept-Encoding

<?xml version="1.0" encoding="utf-8"?><resultat>
[....]
   <farge>Gr..nn</farge>
```

The `..` sequence is how Wireshark displays the non-ASCII bytes that constitutes the UTF-8 multibyte character. So the server headers indicates UTF-8, and the response document itself is correct UTF-8. Yet for some inexplicable reason LWP recodes it to Latin-1. This has got to be a bug, right?

**Comment by genio** [comment] 2017-04-17 01:38
@toreanderson Thanks for looking into this.  It really seems that the problem is in HTTP::Response.  I'm trying to work out exactly what's going wrong so I can put in a proper ticket there.

**Comment by genio** [comment] 2017-04-17 01:46
```->content```

```bash
$ perl -MLWP::UserAgent -E 'say LWP::UserAgent->new()->get("http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002")->content' | grep '<farge>' | hexdump -C
00000000  20 20 20 3c 66 61 72 67  65 3e 47 72 c3 b8 6e 6e  |   <farge>Gr..nn|
00000010  3c 2f 66 61 72 67 65 3e  0a                       |</farge>.|
00000019
```

vs ```->decoded_content```

```bash
 perl -MLWP::UserAgent -E 'say LWP::UserAgent->new()->get("http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002")->decoded_content' | grep '<farge>' | hexdump -C
00000000  42 69 6e 61 72 79 20 66  69 6c 65 20 28 73 74 61  |Binary file (sta|
00000010  6e 64 61 72 64 20 69 6e  70 75 74 29 20 6d 61 74  |ndard input) mat|
00000020  63 68 65 73 0a                                    |ches.|
00000025
```

**Comment by genio** [comment] 2017-04-17 15:08
OK. A test case:

```perl
use strict;
use warnings;
use utf8;

use HTTP::Response;
use Test::More;

# my $url = 'http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002';
# run `curl -is --raw http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002 > result.http`
# get expected hex dump via:
# curl -s 'http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002' | grep '<farge>' | tr -d '[:space:]' | hexdump -C
my $expected = '3C 66 61 72 67 65 3E 47 72 C3 B8 6E 6E 3C 2F 66 61 72 67 65 3E';

my $res = HTTP::Response->parse(<<'EOF');
HTTP/1.1 200 OK
Date: Mon, 17 Apr 2017 14:08:25 GMT
Server: Apache-Coyote/1.1
Expires: Mon, 17 Apr 2017 14:08:25 GMT
Cache-Control: private, max-age=0
ETag: content_86944D3BACBA0B842060C664547D1F5ECDB42B41
Content-Type: text/xml;charset=utf-8
Content-Length: 85
Set-Cookie: JSESSIONID=EE3F389C67E162536CD242E50B29D91E; Path=/; HttpOnly
Vary: Accept-Encoding

<?xml version="1.0" encoding="utf-8"?><resultat>
   <farge>Grønn</farge>
</resultat>
EOF

{
    my $tag = '';
    my $xml = $res->content;
    if ($xml =~ /(<farge>.*)/) {
        $tag = $1;
    }
    isnt($tag, '<farge>Grønn</farge>', '->content: tag does not match expected');
    my $got = sprintf '%*vX', ' ', $tag;
    isnt($got, $expected, '->content: does not match hexdump from curl');
}

{
    my $tag = '';
    my $xml = $res->decoded_content;
    if ($xml =~ /(<farge>.*)/) {
        $tag = $1;
    }
    is($tag, '<farge>Grønn</farge>', '->content: tag matches expected');
    my $got = sprintf '%*vX', ' ', $tag;
    is($got, $expected, '->content: matches hexdump from curl');
}

done_testing();
```

**Comment by toreanderson** [comment] 2017-04-17 17:12
After reading your messages and doing some more testing, I am beginning to think this might be due to brain damage in Perl itself...

I think what is happening is that LWP / HTML::Message gets the UTF-8 data from the web server, recognises it as such and converts it to Perl's internal format, which appears to be Unicode or something like it. So far so good.

When I call `print` on that Unicode/Perl-internal converted string, then Perl for some strange reason ignores my locale settings (which would mean outputting it as UTF-8). Instead it just dumps out the raw Unicode data - which at this point will be indistinguishable from Latin-1, because the special Norwegian characters have the same values in Unicode as in Latin-1.

I can get the expected output in at least these two ways:

1. `perl -C -MLWP::Simple -e "print get('http://www.vegvesen.obilapi?registreringsnummer=EL10002')"`
2. `perl -MLWP::Simple -e "binmode(STDOUT, ':utf8'); print get('http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002')"`

No idea why Perl would ignore my locale settings, but it can't be LWP's fault.

**Comment by karenetheridge** [comment] 2017-04-17 20:21
see `perldoc perllocale`:  "By default, Perl itself (outside the POSIX module) ignores the current locale."

**Comment by Leont** [comment] 2017-04-17 20:38
> I've come across the same issue. It appears LWP::Simple (from libwww-perl version 6.15 on Fedora 25) is recoding the UTF-8 web server response to Latin-1, even though there is nothing nowhere that even hints at this data being in any other character set than UTF-8.

That is because STDOUT is in Latin-1 mode by default for backwards compatibility reasons. `binmode`ing it to `':utf8'` would solve that case. Probably a better solution is to not use `::Simple`…

**Comment by Leont** [comment] 2017-04-17 20:46
> OK. A test case:

That's revealing a replacement character (U+FFFD), probably because the HTTP should be binary not UTF-8.

Also, the hexdump tests seem to be switched around.

With those two fixed, all tests pass for me.

**Comment by genio** [comment] 2017-04-17 22:03
@leont gah.  Thanks for finding my stupid. I've been extra dumb today with this.

```perl
#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use Encode qw(encode);
use HTTP::Response;
use Test::More;

# my $url = 'http://www.vegvesen.no/system/mobilapi?registreringsnummer=EL10002';

# utf-8 characters
my $content = <<'EOF';
HTTP/1.1 200 OK
Date: Mon, 17 Apr 2017 14:08:25 GMT
Server: Apache-Coyote/1.1
Expires: Mon, 17 Apr 2017 14:08:25 GMT
Cache-Control: private, max-age=0
ETag: content_86944D3BACBA0B842060C664547D1F5ECDB42B41
Content-Type: text/xml;charset=utf-8
Content-Length: 85
Set-Cookie: JSESSIONID=EE3F389C67E162536CD242E50B29D91E; Path=/; HttpOnly
Vary: Accept-Encoding

<?xml version="1.0" encoding="utf-8"?><resultat>
   <farge>Grønn</farge>
</resultat>
EOF

# res should be given bytes
my $res = HTTP::Response->parse(encode('UTF-8', $content));
{
    my $tag = '';
    my $xml = $res->content;
    if ($xml =~ /(<farge>.*)/) {
        $tag = $1;
    }
    # bytes
    is($tag, encode('UTF-8', '<farge>Grønn</farge>'), '->content: tag matches expected');
}

{
    my $tag = '';
    my $xml = $res->decoded_content;
    if ($xml =~ /(<farge>.*)/) {
        $tag = $1;
    }
    # characters
    is($tag, "<farge>Grønn</farge>", '->decoded_content: tag matches expected');
}

done_testing();
```

Test behaves as expected.  I'll close this one out for now.

**Closed by genio** 2017-04-17 22:03 UTC
