### ISSUE TITLE
Not timing out for SSL  [rt.cpan.org #60605]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/libwww-perl#219] opened 2017-03-31 19:01 UTC
Migrated from [rt.cpan.org#60605](https://rt.cpan.org/Ticket/Display.html?id=60605) (status was 'open')

Requestors:
* danny@sadinoff.com

From danny@sadinoff.com on 2010-08-22 05:36:47:
```
I'm seeing a scenario where SSL connections aren't timing out properly, while ordinary HTTP 
connections are.  I'll add a better test case in a bit, but in the meantime, I thought i'd mention it.
```

From jgmyers@cpan.org on 2011-11-18 00:22:25:
```
This is a duplicate of #22839
```

**Comment by colinnewell** [comment] 2017-04-09 11:14
This looks like a duplicate of #209 (as suggested in the comments on the original RT).

**Comment by genio** [comment] 2017-04-09 13:20
I'm closing this one out now as it does appear to be a duplicate of #209.  Please yell at me and I'll reopen it if this assertion is incorrect.

Thanks,
Chase

**Closed by genio** 2017-04-09 13:20 UTC
